test:
  image: cypress/base:10
  stage: test
  before_script:
    -npm install -g httpserver
    -npm install cypress
    -npm run start:server
  script:
    -npx cypress run --record --key=c2e6932b-80d9-47b4-ab89-a5f92587a5fb
